name: flyapp
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  build_runner: ^2.1.11
  flutter:
    sdk: flutter
  json_annotation: ^4.0.1
  mobile_scanner: ^3.0.0
  qr_flutter: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^4.1.3

flutter:
  uses-material-design: true
